<a href="https://colab.research.google.com/github/kirnaq/Analysis/blob/main/%D0%9B%D0%B0%D0%B1%D0%B05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Обработка-и-анализ-данных-в-Numpy-массивах" data-toc-modified-id="Обработка-и-анализ-данных-в-Numpy-массивах-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Обработка и анализ данных в Numpy-массивах</a></span></li></ul></div>




# Обработка и анализ данных в Numpy-массивах

<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 1</p>

Дано: списки `a,b=[1,1,1],[3,3,3]`

Создать одномерные массивы A и B из списков а и b.

Вычислить выражение $-((B-А)*(B/2))$

In [ ]:
import numpy as np

In [ ]:

a = [1, 1, 1]
b = [3, 3, 3]

# Создание массивов A и B из списков
A = np.array(a)
B = np.array(b)

result = -((B - A) * (B / 2))

print("Результат:", result)


Результат: [-3. -3. -3.]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 2</p>

Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)), добиться расстановки кодов "шахматных фигур".

Ожидаемый результат:
```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
 ```

In [ ]:
# Создаем пустую шахматную доску 8x8
chessboard = np.zeros((8, 8))

# Расставляем коды шахматных фигур
chessboard[0, :] = [-4, -3, -2, -6, -5, -2, -3, -4]
chessboard[1, :] = [-1] * 8
chessboard[6, :] = [1] * 8
chessboard[7, :] = [4, 3, 2, 6, 5, 2, 3, 4]

print(chessboard)


[[-4. -3. -2. -6. -5. -2. -3. -4.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 4.  3.  2.  6.  5.  2.  3.  4.]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 3</p>

Средствами NumPy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа

In [ ]:
# Создаем массив четных чисел от 2 до 20
even_numbers = np.arange(2, 21, 2)

# Вычисляем ближайшие к четным числам большие нечетные числа
closest_odd_numbers = even_numbers + 1

# Вычисляем произведение четных чисел на ближайшие большие нечетные числа
result = even_numbers * closest_odd_numbers

# Выводим результат
print(result)


[  6  20  42  72 110 156 210 272 342 420]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 4</p>

Сгенерировать двумерный массив *arr* размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0. Значения округлить (с помощью `np.round()`) до четырех десятичных знаков.

In [ ]:
# Генерируем случайный двумерный массив размерности (4, 7) в диапазоне [0, 20]
arr = np.random.uniform(0, 20, size=(4, 7))

# Нормализуем значения массива
min_value = arr.min()
max_value = arr.max()
normalized_arr = (arr - min_value) / (max_value - min_value)

# Округляем значения до четырех десятичных знаков
normalized_arr = np.round(normalized_arr, 4)

# Выводим нормализованный массив
print(normalized_arr)


[[0.4938 0.3062 0.7933 0.7568 0.6507 0.9501 1.    ]
 [0.2625 0.0902 0.6866 0.6455 0.3693 0.6695 0.6056]
 [0.6336 0.8937 0.     0.5379 0.8417 0.8377 0.8957]
 [0.1057 0.8372 0.2707 0.507  0.2816 0.5281 0.931 ]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 5</p>

5. Имеется массив my_array
```
my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
```
Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

In [ ]:
# 5. Ваш код здесь

my_array = np.array([[1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,15],
                    [16,17,18,19,20],
                    [21,22,23,24,25]])

# Извлекаем центральный фрагмент размером 3x3
central_fragment = my_array[1:4, 1:4]

# Выводим результат
print(central_fragment)


[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 6</p>

Создайте массив *my_sin*, состоящий из синусов элементов массива *my_array*.
Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до
трёх цифр после запятой.

In [ ]:
my_array = np.array([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20],
                    [21, 22, 23, 24, 25]])

# Вычисляем синусы элементов массива my_array
my_sin = np.sin(my_array)

# Считаем сумму элементов массива my_sin
sum_of_sin = np.sum(my_sin)

# Округляем результат до трех цифр после запятой
rounded_sum = round(sum_of_sin, 3)

# Выводим результат
print("Сумма синусов элементов массива my_array:", rounded_sum)


Сумма синусов элементов массива my_array: -0.058


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 7</p>

Создать матрицу из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в матрице. Определить индекс этого значения.

In [ ]:
# Создаем матрицу 4x5 случайных целых чисел от 0 до 100
matrix = np.random.randint(0, 101, size=(4, 5))

# Выводим матрицу
print(f"Матрица: {matrix}")

# Получаем второе сверху значение в матрице
second_top_value = matrix[0, 1]  # Вторая строка (индекс 1), первая колонка (индекс 0)

# Находим индекс этого значения
indices = np.where(matrix == second_top_value)
row_index, col_index = indices[0][0], indices[1][0]

# Выводим значение и его индекс
print(f"Второе сверху значение: {second_top_value}")
print(f"Индекс этого значения: ({row_index}, {col_index})")

Матрица: [[41 56  6 66 18]
 [18 50 37 19  4]
 [56 13 17 17 85]
 [50  3 23 32 92]]
Второе сверху значение: 56
Индекс этого значения: (0, 1)
(array([0, 2]), array([1, 0]))


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 8</p>

Задать два двухмерных массива *ar1* и *ar2* размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максимум (минимум, среднее) из двух значений, находящихся на аналогичной позиции в массивах *ar1*, *ar2*.

In [ ]:
# Создаем два массива ar1 и ar2 размерности (4, 7) со случайными целыми числами от 0 до 10
ar1 = np.random.randint(0, 11, (4, 7))
ar2 = np.random.randint(0, 11, (4, 7))

# Выводим исходные массивы
print("ar1:")
print(ar1)

print("\nar2:")
print(ar2)

# Вычисляем максимум, минимум и среднее для каждой пары элементов
max_values = np.maximum(ar1, ar2)
min_values = np.minimum(ar1, ar2)
average_values = (ar1 + ar2) / 2

# Выводим полученные массивы
print("\nМаксимум:")
print(max_values)

print("\nМинимум:")
print(min_values)

print("\nСреднее:")
print(average_values)


ar1:
[[ 6  2  2 10  7  7  2]
 [10  4  2  2  5  1  2]
 [10 10  8  4  9  8  4]
 [ 4  1  6  1  8  8  1]]

ar2:
[[ 0  7  7  2  4  9  9]
 [ 9  9  9 10  1  6  8]
 [10  9  8  0  6  4  0]
 [ 5  4  0  7  3  3  2]]

Максимум:
[[ 6  7  7 10  7  9  9]
 [10  9  9 10  5  6  8]
 [10 10  8  4  9  8  4]
 [ 5  4  6  7  8  8  2]]

Минимум:
[[ 0  2  2  2  4  7  2]
 [ 9  4  2  2  1  1  2]
 [10  9  8  0  6  4  0]
 [ 4  1  0  1  3  3  1]]

Среднее:
[[ 3.   4.5  4.5  6.   5.5  8.   5.5]
 [ 9.5  6.5  5.5  6.   3.   3.5  5. ]
 [10.   9.5  8.   2.   7.5  6.   2. ]
 [ 4.5  2.5  3.   4.   5.5  5.5  1.5]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 9</p>

Имеется массив *great_array*
```
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
```
Чему равна сумма элементов массива great_array, значение которых больше 50?

In [ ]:
#9 Ваш код здесь

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T

# Найдем элементы, значения которых больше 50
filtered_array = great_array[great_array > 50]

# Вычислим сумму этих элементов
sum_of_filtered_values = np.sum(filtered_array)

print("Сумма элементов больше 50:", sum_of_filtered_values)

Сумма элементов больше 50: 5470.0


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 10</p>

Переведите массив *great_array* в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150?

In [ ]:
great_array_flat = great_array.ravel()

# Находим значение элемента с индексом 150
value_at_index_150 = great_array_flat[150]

print("Значение элемента с индексом 150:", value_at_index_150)


Значение элемента с индексом 150: 7.0710678118654755


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 11</p>

Получить индексы, для которых элементы массивов A и B совпадают.
```
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
```
Ожидается результат:

```
array([1, 3, 5, 7])
```

In [ ]:
A = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
B = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Находим индексы, где элементы A и B совпадают
matching_indices = np.where(A == B)[0]

print(matching_indices)

[1 3 5 7]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 12</p>

Создайте три массива: массив четных чисел от 2 до 20, массив ближайших к числам первого массива бОльших нечётных чисел, массив векторного произведения первого массива на второй. Соедините все массивы в один двумерный массив, расположив исходные массивы в столбцах.

In [ ]:
# Создание массива четных чисел от 2 до 20
even_numbers = np.arange(2, 21, 2)

# Создание массива ближайших к четным числам бОльших нечетных чисел
odd_numbers = even_numbers + 1

# Создание массива, который представляет векторное произведение первого и второго массивов
vector_product = even_numbers * odd_numbers

# Объединение всех трех массивов в один двумерный массив
result = np.column_stack((even_numbers, odd_numbers, vector_product))

print(result)


[[  2   3   6]
 [  4   5  20]
 [  6   7  42]
 [  8   9  72]
 [ 10  11 110]
 [ 12  13 156]
 [ 14  15 210]
 [ 16  17 272]
 [ 18  19 342]
 [ 20  21 420]]
